CREATE DATABASE [STARBUCKS] /*!40100 DEFAULT CHARACTER SET utf8 */;

USE [STARBUCKS];

CREATE TABLE [USER] (
    [UID] INT NOT NULL INDENTITY(1, 1),
    [NAME] VARCHAR(45) NOT NULL,
    [EMAIL] VARCHAR(45) NOT NULL,
    [PASSWORD] VARCHAR(45) NOT NULL,
    [ADDRESS] VARCHAR(45) NOT NULL,
    [PHONE] VARCHAR(10) NOT NULL,
    [DATEOFBIRTH] DATE NOT NULL,
    [ROLE] BOOLEAN NOT NULL,
);

CREATE TABLE [CATEGORY] (
    [CID] INT NOT NULL INDENTITY(1, 1) PRIMARY KEY,
    [NAME] VARCHAR(45) NOT NULL,
    [DESCRIPTION] VARCHAR(45) NOT NULL,
);

CREATE TABLE [PRODUCT] (
    [PID] INT NOT NULL INDENTITY(1, 1) PRIMARY KEY,
    [NAME] VARCHAR(45) NOT NULL,
    [PRICE] DECIMAL(10, 2) NOT NULL,
    [DESCRIPTION] VARCHAR(45) NOT NULL,
    [CID] VARCHAR(45) NOT NULL,
    [IMAGE] VARCHAR(45) NOT NULL,
    FOREIGN KEY ([CID]) REFERENCES [CATEGORY]([CID]),
);

CREATE TABLE [ORDER] (
    [OID] INT NOT NULL INDENTITY(1, 1) PRIMARY KEY,
    [UID] INT NOT NULL,
    [PID] INT NOT NULL,
    [QUANTITY] INT NOT NULL,
    [TOTALPRICE] DECIMAL(10, 2) NOT NULL,
    [ORDERDATE] DATE NOT NULL,
    [STATUS] BOOLEAN NOT NULL,
    FOREIGN KEY ([UID]) REFERENCES [USER]([UID]),
    FOREIGN KEY ([PID]) REFERENCES [PRODUCT]([PID]),
);

CREATE TABLE [ORDERDETAIL](
    [ODID] INT NOT NULL INDENTITY(1, 1) PRIMARY KEY,
    [OID] INT NOT NULL,
    [PID] INT NOT NULL,
    [QUANTITY] INT NOT NULL,
    [PRICE] DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY ([OID]) REFERENCES [ORDER]([OID]),
    FOREIGN KEY ([PID]) REFERENCES [PRODUCT]([PID]),
);


CREATE TABLE [RATING] (
    [RID] INT NOT NULL INDENTITY(1, 1) PRIMARY KEY,
    [UID] INT NOT NULL,
    [PID] INT NOT NULL,
    [RATING] INT NOT NULL,
    [COMMENT] VARCHAR(45) NOT NULL,
    FOREIGN KEY ([UID]) REFERENCES [USER]([UID]),
    FOREIGN KEY ([PID]) REFERENCES [PRODUCT]([PID]),
);